foreground              #e4e1e9
background              #1f1f25
selection_foreground    #e1e0f9
selection_background    #444559

cursor                  #bec2ff
cursor_text_color       #262b61

url_color               #e7b9d5

active_border_color     #bec2ff
inactive_border_color   #46464f
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #e0e0ff
active_tab_background   #3d4279
inactive_tab_foreground #c7c5d0
inactive_tab_background #1f1f25
tab_bar_background      #131318

mark1_foreground #262b61
mark1_background #bec2ff
mark2_foreground #2e2f42
mark2_background #c5c4dd
mark3_foreground #45263c
mark3_background #e7b9d5

color0 #46464f
color8 #91909a

color1 #ffb4ab
color9 #93000a

color2  #bec2ff
color10 #e0e0ff

color3  #e7b9d5
color11 #ffd8ee

color4  #c5c4dd
color12 #e1e0f9

color5  #3d4279
color13 #555a92

color6  #444559
color14 #5e3c53

color7  #c7c5d0
color15 #e4e1e9
