foreground              #e2e2e9
background              #1d2024
selection_foreground    #d9e3f9
selection_background    #3e4758

cursor                  #a9c7ff
cursor_text_color       #07305f

url_color               #dcbce1

active_border_color     #a9c7ff
inactive_border_color   #43474e
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #d6e3ff
active_tab_background   #264777
inactive_tab_foreground #c4c6cf
inactive_tab_background #1d2024
tab_bar_background      #111318

mark1_foreground #07305f
mark1_background #a9c7ff
mark2_foreground #273141
mark2_background #bdc7dc
mark3_foreground #3e2845
mark3_background #dcbce1

color0 #43474e
color8 #8e9099

color1 #ffb4ab
color9 #93000a

color2  #a9c7ff
color10 #d6e3ff

color3  #dcbce1
color11 #f9d8fe

color4  #bdc7dc
color12 #d9e3f9

color5  #264777
color13 #405f90

color6  #3e4758
color14 #563e5c

color7  #c4c6cf
color15 #e2e2e9
